### User Authentication API

#### User Signup
POST /api/v1/auth/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}

### Get users
GET  /api/v1/auth/users HTTP/1.1
Host: localhost:3000

### Get users by id
GET  /api/v1/auth/user/1 HTTP/1.1
Host: localhost:3000

### Get user by email
GET  /api/v1/auth/user?email=janedoe@example.com HTTP/1.1
Host: localhost:3000

### Update user
PUT  /api/v1/auth/user/3 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "janedoe@example.com"
}

### Delete user
PATCH   /api/v1/auth/user/4 HTTP/1.1
Host: localhost:3000