### User Authentication API
#### User Signup
### John Doe
POST /api/v1/users/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "password123"
}
### Jane Doe
POST /api/v1/users/signup HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "username": "janedoe",
  "email": "janedoe@example.com",
  "password": "password123"
}

### Signin Jane Doe

POST /api/v1/users/signin HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "email": "janeoe@example.com",
  "password": "password123"
}

### Get users
GET  /api/v1/users HTTP/1.1
Host: localhost:3000

### Get user by email
GET  /api/v1/users/email?email=janedoe@example.com HTTP/1.1
Host: localhost:3000

### Get user by email and/or username
GET /api/v1/users/search?username=janedoe&email=janedoe@example.com HTTP/1.1
Host: localhost:3000


### Update user
PUT  /api/v1/users/3 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "janedoe@example.com"
}

### Delete user
PATCH   /api/v1/users/4 HTTP/1.1
Host: localhost:3000